version: "3.9"
services:
  api:
    build: ./sandra-ultra-backend
    container_name: sandra-ultra-backend
    env_file:
      - ./sandra-ultra-backend/.env
    restart: unless-stopped
    networks:
      - web

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    networks:
      - web

networks:
  web:

volumes:
  caddy_data:
  caddy_config:
