services:
  backend:
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile.backend
    env_file: ../.env
    ports: ["8080:8080"]
  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/Dockerfile.frontend
    env_file: ../.env
    ports: ["3000:3000"]
